package ru.id_sys.schemas.idbank.unifo._2012._1_15;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-21T13:35:14.520+03:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "IDBankUnifoService",
                  wsdlLocation = "file:src/test/resources/wsdl/unifoWS/unifo_1.wsdl",
                  targetNamespace = "http://www.id-sys.ru/schemas/idbank/unifo/2012/1.15/")
public class IDBankUnifoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.id-sys.ru/schemas/idbank/unifo/2012/1.15/", "IDBankUnifoService");
    public final static QName IDBankUnifoPort = new QName("http://www.id-sys.ru/schemas/idbank/unifo/2012/1.15/", "IDBankUnifoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/test/resources/wsdl/unifoWS/unifo_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDBankUnifoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/test/resources/wsdl/unifoWS/unifo_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDBankUnifoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDBankUnifoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDBankUnifoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IDBankUnifoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IDBankUnifoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IDBankUnifoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDBankUnifoPortType
     */
    @WebEndpoint(name = "IDBankUnifoPort")
    public IDBankUnifoPortType getIDBankUnifoPort() {
        return super.getPort(IDBankUnifoPort, IDBankUnifoPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDBankUnifoPortType
     */
    @WebEndpoint(name = "IDBankUnifoPort")
    public IDBankUnifoPortType getIDBankUnifoPort(WebServiceFeature... features) {
        return super.getPort(IDBankUnifoPort, IDBankUnifoPortType.class, features);
    }

}
